# Generated by Django 3.1.7 on 2021-03-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feet',
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_app.feet')),
            ],
            options={
                'db_table': 'leg',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'table',
            },
        ),
        migrations.CreateModel(
            name='TableLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='factory_app.leg')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='factory_app.table')),
            ],
            options={
                'db_table': 'tableleg',
            },
        ),
    ]
